name: Weather Update Every 30 Min (4PM–7PM IST)

on:
  schedule:
    - cron: '0,30 10-13 * * *'  # Every 30 mins from 10:00 to 13:59 UTC (4–7:29 PM IST)
  workflow_dispatch:  # Optional manual trigger

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python weather_script.py
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add weather.json
          git diff --cached --quiet || git commit -m "Update weather.json"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
