name: Update Weather JSON

on:
  schedule:
    - cron: '*/30 10-13 * * *'  # Every 30 mins from 10:00 to 13:30 UTC (4–7 PM IST)
  workflow_dispatch:  # Allows manual run

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run the weather update script
        run: python weather_script.py

      - name: Commit and push changes
        run: |
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git add weather.json
         git diff --cached --quiet || git commit -m "Auto-update weather data"
         git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main

